name: flutter_mobile_engineer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  connectivity_plus: ^3.0.2
  http:
  equatable:
  shared_preferences:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mocktail:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

